<?php
echo "<!DOCTYPE html>\n"; 
echo "<html>\n"; 
echo "<head>\n"; 
echo "    <link type=\"text/css\" rel=\"stylesheet\" href=\"HomePageStyleSheet.css\" />\n"; 
echo "    <title>محافظة اللإسكندرية | دليلك للجامعات بمصر</title>\n"; 
echo "	<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n"; 
echo "</head>\n"; 
echo "\n"; 
echo "<body dir=\"rtl\">\n"; 
echo "\n"; 
echo "    <div class=\"header\">\n"; 
echo "        <nav class=\"menu\">\n"; 
echo "            <ul>\n"; 
echo "                <li><a href=\"HomePage.php\">الرئيسية</a></li>\n"; 
echo "                <li class=\"current\"><a href=\"#\">ابحث عن جامعة</a></li>\n"; 
echo "                <li><a href=\"#\">روابط مفيدة</a></li>\n"; 
echo "                <li><a href=\"#\">تواصل معنا</a></li>\n"; 
echo "            </ul>\n"; 
echo "        </nav>\n"; 
echo "    </div>\n"; 
echo "\n"; 
echo "    <div class=\"main-city\">\n"; 
echo "        <p><bold>محافظة الأسكندرية</bold></p>\n"; 
echo "        <p>1. جامعة الأسكندرية :</p>\n"; 
echo "        <a href=\"http://www.alexu.edu.eg/index.php/ar/\"><img src=\"alexu_logo.png\" /></a>\n"; 
echo "        <a href=\"http://www.alexu.edu.eg/index.php/ar/\"><img src=\"alexu.jpg\" /></a>\n"; 
echo "        <ul class=\"faculties\">\n"; 
echo "            <li><a href=\"http://arts.alexu.edu.eg/ar/\">كلية الآداب</a></li>\n"; 
echo "            <li><a href=\"http://law.alexu.edu.eg/\">كلية الحقوق</a></li>\n"; 
echo "            <li><a href=\"http://Comm.alexu.edu.eg/\">كلية التجارة</a></li>\n"; 
echo "            <li><a href=\"http://edu.alexu.edu.eg/\">كلية التربية</a></li>\n"; 
echo "            <li><a href=\"FacultyPage.php\">كلية الهندسة</a></li>\n"; 
echo "            <li><a href=\"http://sci.alexu.edu.eg/ar/\">كلية العلوم</a></li>\n"; 
echo "            <li><a href=\"http://www.agr.alexu.edu.eg/\">كلية الزراعة</a></li>\n"; 
echo "            <li><a href=\"http://www.med.alexu.edu.eg/\">كلية الطب</a></li>\n"; 
echo "            <li><a href=\"http://dent.alexu.edu.eg/\">كلية طب الأسنان</a></li>\n"; 
echo "            <li><a href=\"http://www.pharmacy.alexu.edu.eg/\">كلية الصيدلة </a></li>\n"; 
echo "            <li><a href=\"http://www.nurs.alexu.edu.eg/\">كلية التمريض</a></li>\n"; 
echo "            <li><a href=\"http://vet.alexu.edu.eg/\">كلية الطب البيطرى</a></li>\n"; 
echo "            <li><a href=\"http://tourism.alexu.edu.eg/\">كلية السياحة والفنادق</a></li>\n"; 
echo "            <li><a href=\"http://edusp.alexu.edu.eg/\">كلية التربية النوعية</a></li>\n"; 
echo "            <li><a href=\"http://esps.alexu.edu.eg/\">كلية الدراسات الاقتصادية والعلوم السياسية </a></li>\n"; 
echo "            <li><a href=\"http://kindg.alexu.edu.eg/\">كلية رياض الأطفال</a></li>\n"; 
echo "\n"; 
echo "            <li><a href=\"http://finearts.alexu.edu.eg/\">كلية الفنون الجميلة</a></li>\n"; 
echo "            <li><a href=\"http://fpeg.alexu.edu.eg/\">كلية التربية الرياضية للبنات</a></li>\n"; 
echo "            <li><a href=\"http://sea.alexu.edu.eg/\">كلية التربية الرياضية بنين</a></li>\n"; 
echo "\n"; 
echo "            <li><a href=\"http://agrsaba.alexu.edu.eg/\">كلية الزراعة سابا باشا</a></li>\n"; 
echo "\n"; 
echo "            <li><a href=\"http://hiph.alexu.edu.eg/\">المعهد العالى للصحة العامة</a></li>\n"; 
echo "        </ul>\n"; 
echo "\n"; 
echo "        <p>2. الأكاديمية العربية للعلوم و التكنولوجيا و النقل البحري :</p>\n"; 
echo "        <a href=\"http://www.aast.edu/en/colleges/\"><img src=\"Aast_logo.gif\" /></a>\n"; 
echo "        <ul ckass=\"faculties\">\n"; 
echo "            <li><a href=\"http://www.aast.edu/en/deaneries/admission-web/contenttemp.php?page_id=38700013\">فرع أبوقير</a></li>\n"; 
echo "            <li><a href=\"http://www.aast.edu/en/deaneries/admission-web/contenttemp.php?page_id=38700013\">فرع ميامي</a></li>\n"; 
echo "        </ul>\n"; 
echo "    </div>\n"; 
echo "\n"; 
echo "    <div class=\"footer\">\n"; 
echo "\n"; 
echo "    </div>\n"; 
echo "\n"; 
echo "</body>\n"; 
echo "</html>\n"; 
echo "\n";
?>