<?php
echo "<!DOCTYPE html>\n"; 
echo "<html>\n"; 
echo "<head>\n"; 
echo "    <link type=\"text/css\" rel=\"stylesheet\" href=\"HomePageStyleSheet.css\" />\n"; 
echo "    <title></title>\n"; 
echo "    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n"; 
echo "</head>\n"; 
echo "<body dir=\"rtl\">\n"; 
echo "    <div class=\"header\">\n"; 
echo "        <nav class=\"menu\">\n"; 
echo "            <ul>\n"; 
echo "                <li><a href=\"HomePage.php\">الرئيسية</a></li>\n"; 
echo "                <li class=\"current\"><a href=\"#\">ابحث عن جامعة</a></li>\n"; 
echo "                <li><a href=\"#\">روابط مفيدة</a></li>\n"; 
echo "                <li><a href=\"#\">تواصل معنا</a></li>\n"; 
echo "            </ul>\n"; 
echo "        </nav>\n"; 
echo "    </div>\n"; 
echo "\n"; 
echo "    <div class=\"main\">\n"; 
echo "        <p><bold>[uniName]</bold></p>\n"; 
echo "        <p><bold>[facName]</bold></p>\n"; 
echo "        <img src=\"[facImgURL]\" title=\"Faculty photo\" />\n"; 
echo "        <ul class=\"facInfo\">\n"; 
echo "            <li><p>القسم: [deptName]</p></li>\n"; 
echo "            <li><p>[deptDecription]</p></li>\n"; 
echo "            <li><p>شروط القبول:</p>\n"; 
echo "                <ul><li><p>مجموع تراكمي [deptGpa]</p></li></ul>\n"; 
echo "            </li>\n"; 
echo "            <li><p>الكورسات:</p>\n"; 
echo "                <ul>[CourseList]</ul>\n"; 
echo "            </li>\n"; 
echo "        </ul>\n"; 
echo "\n"; 
echo "    </div>\n"; 
echo "\n"; 
echo "    <div class=\"footer\">\n"; 
echo "    </div>\n"; 
echo "</body>\n"; 
echo "</html>\n"; 
echo "\n";
?>