<?php
echo "<!DOCTYPE html>\n"; 
echo "<html>\n"; 
echo "<head>\n"; 
echo "    <link type=\"text/css\" rel=\"stylesheet\" href=\"HomePageStyleSheet.css\" />\n"; 
echo "    <title></title>\n"; 
echo "	<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n"; 
echo "</head>\n"; 
echo "\n"; 
echo "<body dir=\"rtl\">\n"; 
echo "    <div class=\"header\">\n"; 
echo "        <nav class=\"menu\">\n"; 
echo "            <ul>\n"; 
echo "                <li><a href=\"HomePage.php\">الرئيسية</a></li>\n"; 
echo "                <li class=\"current\"><a href=\"#\">ابحث عن جامعة</a></li>\n"; 
echo "                <li><a href=\"#\">روابط مفيدة</a></li>\n"; 
echo "                <li><a href=\"#\">تواصل معنا</a></li>\n"; 
echo "            </ul>\n"; 
echo "        </nav>\n"; 
echo "    </div>\n"; 
echo "\n"; 
echo "    <div class=\"main\">\n"; 
echo "        <p><bold>[uniName]</bold></p>\n"; 
echo "        <p><bold>[facName]</bold></p>\n"; 
echo "        <img src=\"FOE.jpg\" title=\"Faculty photo\"/>\n"; 
echo "        <ul class=\"facInfo\">\n"; 
echo "            <li><p>العنوان: [facAddress]</p></li>\n"; 
echo "            <li><p>تليفون: [facPhone]</p></li>\n"; 
echo "            <li><p>موقع: [facWebsite]</p></li>\n"; 
echo "            <li><p>شروط القبول:</p>\n"; 
echo "                <ol>\n"; 
echo "                    <li><p>علمي علوم: [sciGrade]</p></li>\n"; 
echo "                    <li><p>علمي رياضة: [mathGrade]</p></li>\n"; 
echo "                    <li><p>أدبي: [litGrade]</p></li>\n"; 
echo "                </ol>\n"; 
echo "            </li>\n"; 
echo "            <li><p>الأقسام:</p>\n"; 
echo "                <ol><p>[deptList]</p></ol>\n"; 
echo "            </li>\n"; 
echo "        </ul>\n"; 
echo "\n"; 
echo "    </div>\n"; 
echo "\n"; 
echo "    <div class=\"footer\">\n"; 
echo "    </div>\n"; 
echo "</body>\n"; 
echo "</html>\n"; 
echo "\n";
?>