<?php
echo "<!DOCTYPE html>\n"; 
echo "<html>\n"; 
echo "<head>\n"; 
echo "    <link type=\"text/css\" rel=\"stylesheet\" href=\"HomePageStyleSheet.css\" />\n"; 
echo "    <title>دليلك للجامعات بمصر</title>\n"; 
echo "    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n"; 
echo "</head>\n"; 
echo "\n"; 
echo "<body dir=\"rtl\">\n"; 
echo "\n"; 
echo "    <div class=\"header\">\n"; 
echo "        <nav class=\"menu\">\n"; 
echo "            <ul>\n"; 
echo "                <li class=\"current\"><a href=\"HomePage.php\">الرئيسية</a></li>\n"; 
echo "                <li><a href=\"#\">ابحث عن جامعة</a></li>\n"; 
echo "                <li><a href=\"#\">روابط مفيدة</a></li>\n"; 
echo "                <li><a href=\"#\">تواصل معنا</a></li>\n"; 
echo "            </ul>\n"; 
echo "        </nav>\n"; 
echo "    </div>\n"; 
echo "\n"; 
echo "    <div class=\"main\">\n"; 
echo "\n"; 
echo "        <p><bold>مرحبا بك في دليلك للجامعات بمصر</bold></p>\n"; 
echo "        <img src=\"Egypt-full.png\" alt=\"\" usemap=\"#Map\" />\n"; 
echo "\n"; 
echo "        <map name=\"Map\" id=\"Map\">\n"; 
echo "\n"; 
echo "            <area alt=\"الوادي الجديد\" title=\"الوادي الجديد\" href=\"#\" shape=\"rect\" coords=\"166,377,310,447\" />\n"; 
echo "            <area alt=\"أسوان\" title=\"أسوان\" href=\"#\" shape=\"rect\" coords=\"440,467,494,498\" />\n"; 
echo "            <area alt=\"الأقصر\" title=\"الأقصر\" href=\"#\" shape=\"rect\" coords=\"447,385,482,407\" />\n"; 
echo "            <area alt=\"قنا\" title=\"قنا\" href=\"#\" shape=\"rect\" coords=\"464,352,495,372\" />\n"; 
echo "            <area alt=\"سوهاج\" title=\"سوهاج\" href=\"#\" shape=\"rect\" coords=\"415,318,451,341\" />\n"; 
echo "            <area alt=\"أسيوط\" title=\"أسيوط\" href=\"#\" shape=\"rect\" coords=\"385,273,430,295\" />\n"; 
echo "            <area alt=\"البحر الأحمر\" title=\"البحر الأحمر\" href=\"#\" shape=\"rect\" coords=\"483,303,563,407\" />\n"; 
echo "            <area alt=\"المنيا\" title=\"المنيا\" href=\"#\" shape=\"rect\" coords=\"325,222,384,247\" />\n"; 
echo "            <area alt=\"بني سويف\" title=\"بني سويف\" href=\"#\" shape=\"rect\" coords=\"388,197,346,183\" />\n"; 
echo "            <area alt=\"السادس من أكتوبر\" title=\"السادس من أكتوبر\" href=\"#\" shape=\"poly\" coords=\"303,152,306,194,259,202,263,177\" />\n"; 
echo "            <area alt=\"الفيوم\" title=\"الفيوم\" href=\"#\" shape=\"rect\" coords=\"364,176,331,158\" />\n"; 
echo "            <area alt=\"حلوان\" title=\"حلوان\" href=\"#\" shape=\"rect\" coords=\"413,159,378,139\" />\n"; 
echo "            <area alt=\"جنوب سيناء\" title=\"جنوب سيناء\" href=\"#\" shape=\"rect\" coords=\"553,204,496,165\" />\n"; 
echo "            <area alt=\"شمال سيناء\" title=\"شمال سيناء\" href=\"#\" shape=\"rect\" coords=\"540,111,489,81\" />\n"; 
echo "            <area alt=\"السويس\" title=\"السويس\" href=\"#\" shape=\"rect\" coords=\"469,131,426,107\" />\n"; 
echo "            <area alt=\"اللإسماعيلية\" title=\"اللإسماعيلية\" href=\"#\" shape=\"rect\" coords=\"462,101,419,83\" />\n"; 
echo "            <area alt=\"بورسعيد\" title=\"بورسعيد\" href=\"#\" shape=\"rect\" coords=\"458,67,420,43\" />\n"; 
echo "            <area alt=\"الشرقية\" title=\"الشرقية\" href=\"#\" shape=\"rect\" coords=\"417,84,386,73\" />\n"; 
echo "            <area alt=\"الدقهلية\" title=\"الدقهلية\" href=\"#\" shape=\"rect\" coords=\"415,63,380,49\" />\n"; 
echo "            <area alt=\"دمياط\" title=\"دمياط\" href=\"#\" shape=\"rect\" coords=\"416,43,381,29\" />\n"; 
echo "            <area alt=\"القاهرة\" title=\"القاهرة\" href=\"#\" shape=\"rect\" coords=\"409,132,378,116\" />\n"; 
echo "            <area alt=\"الجيزة\" title=\"الجيزة\" href=\"#\" shape=\"rect\" coords=\"372,130,345,110\" />\n"; 
echo "            <area alt=\"القليوبية\" title=\"القليوبية\" href=\"#\" shape=\"rect\" coords=\"397,110,362,99\" />\n"; 
echo "            <area alt=\"المنوفية\" title=\"المنوفية\" href=\"#\" shape=\"rect\" coords=\"386,94,345,77\" />\n"; 
echo "            <area alt=\"الغربية\" title=\"الغربية\" href=\"#\" shape=\"rect\" coords=\"383,73,348,61\" />\n"; 
echo "            <area alt=\"كفر الشيخ\" title=\"كفر الشيخ\" href=\"#\" shape=\"rect\" coords=\"384,52,341,38\" />\n"; 
echo "            <area alt=\"البحيرة\" title=\"البحيرة\" href=\"#\" shape=\"rect\" coords=\"343,67,318,78\" />\n"; 
echo "            <area alt=\"الاسكندرية\" title=\"الاسكندرية\" href=\"alexandria.php\" shape=\"rect\" coords=\"308,54,263,65\" />\n"; 
echo "            <area alt=\"مطروح\" title=\"مطروح\" href=\"#\" shape=\"rect\" coords=\"213,107,138,134\" />\n"; 
echo "        </map>\n"; 
echo "\n"; 
echo "        <p>اضغط اسم المحافظة من أجل معلومات عن الجامعات التي توجد بها</p>\n"; 
echo "    </div>\n"; 
echo "    <div class=\"footer\">\n"; 
echo "\n"; 
echo "    </div>\n"; 
echo "</body>\n"; 
echo "</html>\n";
?>